import { useMemo, useState } from "react";
import type { FormEvent, ReactNode } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { useCreateExpense, useDeleteExpense, useGetMonthlySummary, useListExpenses, useUpdateExpense, getListExpensesQueryKey, getGetMonthlySummaryQueryKey } from "@workspace/api-client-react";
import type { Expense, ExpenseInput } from "@workspace/api-client-react";
import { ArrowUpRight, CalendarDays, CircleDollarSign, Loader2, Pencil, Plus, ReceiptText, RefreshCw, Sparkles, Trash2, X } from "lucide-react";

const categories = ["Utilities", "Bazar", "One-Time"] as const;
type Category = typeof categories[number];
const categoryColor: Record<Category, string> = { Utilities: "#42647b", Bazar: "#c49435", "One-Time": "#bf6654" };
const monthNow = new Date().toISOString().slice(0, 7);
const money = (n: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(n);
const dateOnly = (d: string) => d.slice(0, 10);
const prettyDate = (d: string) => new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" }).format(new Date(`${dateOnly(d)}T12:00:00`));
const titleCase = (s: string) => s.replace("-", " ").replace(/\b\w/g, c => c.toUpperCase());

function Field({ label, children }: { label: string; children: ReactNode }) {
  return <label className="grid gap-1.5 text-[11px] font-semibold uppercase tracking-[.13em] text-muted-foreground"><span>{label}</span>{children}</label>;
}

function ExpenseForm({ initial, onDone, onCancel }: { initial?: Expense; onDone: () => void; onCancel?: () => void }) {
  const create = useCreateExpense(); const update = useUpdateExpense();
  const [form, setForm] = useState<ExpenseInput>({ title: initial?.title ?? "", amount: initial?.amount ?? 0, category: initial?.category ?? "Bazar", date: initial ? dateOnly(initial.date) : new Date().toISOString().slice(0, 10), type: initial?.type ?? "one-time" });
  const set = (key: keyof ExpenseInput, value: string | number) => setForm(v => ({ ...v, [key]: value }));
  const pending = create.isPending || update.isPending;
  const submit = (e: FormEvent) => { e.preventDefault(); if (!form.title.trim() || Number(form.amount) <= 0) return; const data = { data: { ...form, title: form.title.trim(), amount: Number(form.amount) } }; initial ? update.mutate({ id: initial.id, ...data }, { onSuccess: onDone }) : create.mutate(data, { onSuccess: onDone }); };
  return <form onSubmit={submit} className="grid gap-4">
    <div className="flex items-center justify-between"><h3 className="font-serif text-2xl">{initial ? "Edit expense" : "Add an expense"}</h3>{onCancel && <button type="button" onClick={onCancel} aria-label="Close form" data-testid="button-close-form" className="rounded-full p-2 text-muted-foreground hover:bg-muted"><X size={18}/></button>}</div>
    <Field label="What was it?"><input autoFocus value={form.title} onChange={e => set("title", e.target.value)} placeholder="e.g. Electric bill" data-testid="input-expense-title" className="h-11 rounded-lg border bg-background px-3 outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/10" /></Field>
    <div className="grid grid-cols-2 gap-3"><Field label="Amount"><div className="relative"><span className="absolute left-3 top-2.5 text-muted-foreground">$</span><input type="number" min="0.01" step="0.01" value={form.amount || ""} onChange={e => set("amount", Number(e.target.value))} placeholder="0.00" data-testid="input-expense-amount" className="h-11 w-full rounded-lg border bg-background pl-7 pr-3 outline-none focus:border-primary" /></div></Field><Field label="Date"><input type="date" value={form.date} onChange={e => set("date", e.target.value)} data-testid="input-expense-date" className="h-11 rounded-lg border bg-background px-3 outline-none focus:border-primary" /></Field></div>
    <Field label="Category"><div className="grid grid-cols-3 gap-2">{categories.map(c => <button type="button" key={c} onClick={() => set("category", c)} data-testid={`button-category-${c}`} className={`rounded-lg border px-2 py-2.5 text-xs font-semibold transition ${form.category === c ? "border-primary bg-primary text-primary-foreground" : "bg-background hover:bg-muted"}`}>{c}</button>)}</div></Field>
    <Field label="Frequency"><div className="grid grid-cols-2 gap-2">{(["one-time", "recurring"] as const).map(t => <button type="button" key={t} onClick={() => set("type", t)} data-testid={`button-type-${t}`} className={`rounded-lg border px-3 py-2.5 text-sm capitalize transition ${form.type === t ? "border-primary bg-primary text-primary-foreground" : "bg-background hover:bg-muted"}`}>{t}</button>)}</div></Field>
    <button disabled={pending} data-testid="button-save-expense" className="mt-1 flex h-11 items-center justify-center gap-2 rounded-lg bg-primary font-semibold text-primary-foreground transition hover:-translate-y-0.5 disabled:opacity-60">{pending && <Loader2 size={16} className="animate-spin"/>}{initial ? "Save changes" : "Add to ledger"}</button>
  </form>;
}

export default function Dashboard() {
  const queryClient = useQueryClient(); const [showForm, setShowForm] = useState(false); const [editing, setEditing] = useState<Expense>(); const [deleting, setDeleting] = useState<number>(); const [filter, setFilter] = useState<Category | "All">("All");
  const list = useListExpenses({ query: { queryKey: getListExpensesQueryKey() } }); const summary = useGetMonthlySummary({ month: monthNow }, { query: { queryKey: getGetMonthlySummaryQueryKey({ month: monthNow }) } }); const remove = useDeleteExpense();
  const expenses = useMemo(() => (list.data ?? []).filter(e => e.date.startsWith(monthNow)).sort((a, b) => b.date.localeCompare(a.date)), [list.data]);
  const visible = filter === "All" ? expenses : expenses.filter(e => e.category === filter);
  const total = summary.data?.total ?? expenses.reduce((sum, e) => sum + e.amount, 0); const count = summary.data?.transactionCount ?? expenses.length;
  const grouped = useMemo(() => categories.map(category => ({ category, total: summary.data?.byCategory?.find(c => c.category === category)?.total ?? expenses.filter(e => e.category === category).reduce((s, e) => s + e.amount, 0) })), [summary.data, expenses]);
  const refresh = () => { void queryClient.invalidateQueries({ queryKey: getListExpensesQueryKey() }); void queryClient.invalidateQueries({ queryKey: getGetMonthlySummaryQueryKey({ month: monthNow }) }); };
  const done = () => { setShowForm(false); setEditing(undefined); refresh(); };
  return <div className="grain min-h-[100dvh] bg-background">
    <aside className="fixed inset-y-0 left-0 z-10 hidden w-[238px] flex-col bg-sidebar px-6 py-7 text-sidebar-foreground md:flex">
      <div className="flex items-center gap-2.5"><div className="grid size-8 place-items-center rounded-lg bg-sidebar-primary text-sidebar-primary-foreground"><CircleDollarSign size={19}/></div><span className="font-serif text-[25px] tracking-tight">expanse</span></div>
      <div className="mt-16 text-[10px] font-semibold uppercase tracking-[.18em] text-sidebar-foreground/45">Your money, clearly</div>
      <nav className="mt-4 grid gap-1"><button data-testid="nav-dashboard" className="flex items-center gap-3 rounded-lg bg-sidebar-accent px-3 py-3 text-left text-sm font-semibold"><ReceiptText size={17} className="text-sidebar-primary"/>Overview</button></nav>
      <div className="mt-auto rounded-xl border border-sidebar-border bg-sidebar-accent/60 p-4"><Sparkles size={16} className="mb-3 text-sidebar-primary"/><p className="text-sm leading-5">Small entries make a steady picture.</p><p className="mt-2 text-xs text-sidebar-foreground/50">Keep going, one day at a time.</p></div>
    </aside>
    <main className="md:ml-[238px]"><header className="flex items-center justify-between border-b border-border/70 px-5 py-5 md:px-10 md:py-7"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-muted-foreground">Personal ledger</p><h1 className="mt-1 font-serif text-3xl tracking-tight md:text-4xl">Good morning, Alex<span className="text-accent">.</span></h1></div><div className="flex items-center gap-3"><button onClick={refresh} data-testid="button-refresh" aria-label="Refresh expenses" className="hidden rounded-full border bg-card p-2.5 text-muted-foreground transition hover:-rotate-12 hover:text-foreground sm:block"><RefreshCw size={17}/></button><button onClick={() => { setEditing(undefined); setShowForm(true); }} data-testid="button-quick-add" className="flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground shadow-sm transition hover:-translate-y-0.5"><Plus size={17}/> <span className="hidden sm:inline">Quick add</span></button></div></header>
      <div className="mx-auto max-w-[1240px] px-5 py-7 md:px-10 md:py-10"><div className="grid gap-5 lg:grid-cols-[1.35fr_1fr]">
        <section className="relative overflow-hidden rounded-2xl bg-primary p-6 text-primary-foreground shadow-lg md:p-8 rise"><div className="absolute -right-10 -top-16 size-64 rounded-full border-[28px] border-accent/20"/><div className="absolute -bottom-24 right-28 size-56 rounded-full border border-sidebar-primary/20"/><div className="relative"><div className="flex items-center justify-between"><p className="text-sm text-primary-foreground/65">Spent in {new Intl.DateTimeFormat("en-US", { month: "long" }).format(new Date())}</p><CalendarDays size={18} className="text-accent"/></div><p data-testid="text-total-expenses" className="mt-7 font-mono text-5xl tracking-[-.08em] md:text-6xl">{money(total)}</p><div className="mt-7 flex items-end justify-between"><p className="text-sm text-primary-foreground/60"><span data-testid="text-transaction-count" className="font-semibold text-primary-foreground">{count}</span> transactions recorded</p><span className="flex items-center gap-1 rounded-full bg-accent px-2.5 py-1 text-xs font-bold text-accent-foreground"><ArrowUpRight size={14}/> this month</span></div></div></section>
        <section className="rounded-2xl border bg-card p-6 shadow-sm md:p-8 rise delay-1"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-muted-foreground">The shape of it</p><h2 className="mt-1 font-serif text-2xl">By category</h2></div><span className="font-mono text-xs text-muted-foreground">{monthNow.replace("-", " / ")}</span></div><div className="mt-6 grid gap-4">{grouped.map(({ category, total: amount }) => { const pct = total ? (amount / total) * 100 : 0; return <div key={category} data-testid={`category-row-${category}`}><div className="mb-1.5 flex justify-between text-sm"><span className="font-medium">{category}</span><span className="font-mono text-xs text-muted-foreground">{money(amount)}</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full transition-all duration-700" style={{ width: `${pct}%`, backgroundColor: categoryColor[category] }}/></div></div>})}</div></section>
      </div>
      <section className="mt-8 rise delay-2"><div className="mb-4 flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-muted-foreground">The paper trail</p><h2 className="mt-1 font-serif text-3xl">Recent expenses</h2></div><div className="flex gap-1 rounded-lg bg-muted p-1">{(["All", ...categories] as const).map(c => <button key={c} onClick={() => setFilter(c)} data-testid={`button-filter-${c}`} className={`rounded-md px-2.5 py-1.5 text-xs font-semibold transition ${filter === c ? "bg-card text-foreground shadow-sm" : "text-muted-foreground hover:text-foreground"}`}>{c}</button>)}</div></div>
        <div className="overflow-hidden rounded-2xl border bg-card shadow-sm">{list.isLoading ? <div className="grid gap-3 p-5">{[1,2,3].map(i => <div key={i} className="h-14 animate-pulse rounded-lg bg-muted"/>)}</div> : list.isError ? <div className="grid place-items-center gap-2 p-14 text-center"><p className="font-serif text-2xl">Couldn’t open the ledger</p><p className="text-sm text-muted-foreground">Something interrupted the connection.</p><button onClick={() => list.refetch()} data-testid="button-retry-expenses" className="mt-2 flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold hover:bg-muted"><RefreshCw size={14}/> Try again</button></div> : visible.length === 0 ? <div className="grid place-items-center gap-3 p-14 text-center"><div className="grid size-12 place-items-center rounded-full bg-accent/25 text-primary"><ReceiptText size={22}/></div><p className="font-serif text-2xl">{filter === "All" ? "A clean page." : `No ${filter.toLowerCase()} yet.`}</p><p className="max-w-xs text-sm text-muted-foreground">Add the first expense and your month will start to take shape.</p><button onClick={() => setShowForm(true)} data-testid="button-empty-add" className="mt-1 flex items-center gap-1.5 rounded-lg bg-primary px-3 py-2 text-sm font-semibold text-primary-foreground"><Plus size={15}/> Add expense</button></div> : <div>{visible.slice(0, 8).map((expense, index) => <div key={expense.id} data-testid={`row-expense-${expense.id}`} className="group flex items-center gap-3 border-b px-4 py-4 last:border-0 md:px-6"><div className="grid size-10 shrink-0 place-items-center rounded-xl text-sm font-bold" style={{ backgroundColor: `${categoryColor[expense.category]}18`, color: categoryColor[expense.category] }}>{expense.title.slice(0,1).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{expense.title}</p><div className="mt-1 flex items-center gap-2 text-xs text-muted-foreground"><span>{expense.category}</span><span className="size-1 rounded-full bg-border"/><span>{prettyDate(expense.date)}</span>{expense.type === "recurring" && <><span className="size-1 rounded-full bg-border"/><span className="text-primary">Recurring</span></>}</div></div><span className="font-mono text-sm font-medium">{money(expense.amount)}</span><div className="flex gap-1 opacity-100 transition md:opacity-0 md:group-hover:opacity-100"><button onClick={() => { setEditing(expense); setShowForm(true); }} aria-label={`Edit ${expense.title}`} data-testid={`button-edit-expense-${expense.id}`} className="rounded-md p-2 text-muted-foreground hover:bg-muted hover:text-foreground"><Pencil size={15}/></button><button onClick={() => setDeleting(expense.id)} aria-label={`Delete ${expense.title}`} data-testid={`button-delete-expense-${expense.id}`} className="rounded-md p-2 text-muted-foreground hover:bg-destructive/10 hover:text-destructive"><Trash2 size={15}/></button></div></div>)}</div>}</div>
      </section>
      <footer className="mt-8 flex items-center justify-between border-t border-border/70 pt-5 text-xs text-muted-foreground"><span>Expanse · a calmer view of spending</span><span className="font-mono">{expenses.length} this month</span></footer></div>
    </main>
    {showForm && <div className="fixed inset-0 z-30 grid items-end bg-primary/20 p-0 backdrop-blur-sm sm:items-center sm:p-5"><div className="w-full rounded-t-2xl border bg-card p-6 shadow-lg sm:mx-auto sm:max-w-md sm:rounded-2xl"><ExpenseForm initial={editing} onDone={done} onCancel={() => { setShowForm(false); setEditing(undefined); }}/></div></div>}
    {deleting && <div className="fixed inset-0 z-40 grid place-items-center bg-primary/25 p-5 backdrop-blur-sm"><div className="w-full max-w-sm rounded-2xl border bg-card p-6 shadow-lg"><div className="grid size-11 place-items-center rounded-full bg-destructive/10 text-destructive"><Trash2 size={20}/></div><h3 className="mt-4 font-serif text-2xl">Remove this entry?</h3><p className="mt-1 text-sm text-muted-foreground">This can’t be undone, but your other entries will stay right where they are.</p><div className="mt-6 flex justify-end gap-2"><button onClick={() => setDeleting(undefined)} data-testid="button-cancel-delete" className="rounded-lg border px-4 py-2 text-sm font-semibold hover:bg-muted">Keep it</button><button disabled={remove.isPending} onClick={() => remove.mutate({ id: deleting }, { onSuccess: () => { setDeleting(undefined); refresh(); }})} data-testid="button-confirm-delete" className="flex items-center gap-2 rounded-lg bg-destructive px-4 py-2 text-sm font-semibold text-destructive-foreground disabled:opacity-60">{remove.isPending && <Loader2 size={14} className="animate-spin"/>}Remove</button></div></div></div>}
  </div>;
}